services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ../../data/neo4j/logs:/logs
      - ../../data/neo4j/config:/config
      - ../../data/neo4j/data:/data
      - ../../data/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always